export const ERVAS_INFO = {
  usar_ervas: "As plantas tem a virtude de expelir todas as toxinas do nosso organismo, purificando-o e suprimindo a falta de certos elementos nutritivos. Não foi em vão que Deus criou a rica natureza com tão variada flora medicinal. E é nessa Natureza que o homem encontra seu equilíbrio energético.\n\nA finalidade dos banhos dentro da Umbanda é purificar, limpar e energizar.\n\nNos banhos são utilizadas ervas, as quais, já têm sua eficiência comprovada pela ciência e são largamente utilizadas em forma de medicamentos pela indústria farmacêutica e de manipulação.\n\nCada erva ou conjunto de ervas têm sua finalidade em relação a um ou mais tipos de problemas, doenças, e baixas energéticas.\n\nNão basta tomar o banho. Tem que se ter fé naquilo que se está fazendo, consciência de sua utilidade, finalidade e benesses.",
  cuidados: "Identificação: Tudo começa com a identificação correta das espécies que se deseja utilizar. Deve-se tomar cuidado com a confusão causada pelo excesso de nomes vulgares, populares ou regionais.\n\nColeta: Depois de saber qual planta será utilizada, há a necessidade de alguns cuidados na hora da colheita. Poderemos fazer uma coleta parcial (raiz, casca, semente, flor, folha, fruto) ou total (toda a planta). E ainda nunca esquecer de fazer as saudações necessárias (Ossae, Oxossi, Jurema), sempre com muito respeito.\n\nArmazenagem: Sempre manter em local seco arejado e protegido das crianças e animais domésticos.",
  uso_interno: "Chás - Fornecem substancias terapêuticas, hidratam, estimulam, desintoxicam, controlam a temperatura e auxiliam na digestão. São três tipos:\n\n* Chá em maceração: Mergulhar a erva em água (fervida ou filtrada), macerar, tapar bem o recipiente, deixar por horas, dias ou até semanas, depois coar e tomar.\n\n* Chá em infusão: Picar a erva, colocar num recipiente e derramar água fervente sobre elas. Tapar e deixar de 5 a 15 minutos, coar e tomar ainda quente.\n\n* Chá em decocção: Picar a erva e acrescentar água fria, levar ao fogo por 5 a 10 minutos, coar e tomar ainda quente.",
  uso_externo: "Quando tomamos um Banho de Ervas limpamos a nossa aura fazendo com que ela volte a funcionar normalmente e harmonizando os nossos chakras que são túneis por onde entram as energias no nosso corpo físico.\n\n* Banhos de ervas verdes: Quando usamos ervas verdes, estas devem ser maceradas na água e nunca fervidas pois a energia e o sumo obtido podem ser evaporados.\n\n* Banhos de ervas secas: Devemos misturar em água fria e levar ao fogo até ferver para que com o calor se desprenda a vitalidade da planta.",
  banhos_especificos: [
    { nome: "Descarrego", ervas: "arruda, guiné e casca de alho" },
    { nome: "Abre caminho", ervas: "Erva Abre caminho, levante e louro" },
    { nome: "Tirar mágoas", ervas: "Folhas de colônia, Malva e Camomila" },
    { nome: "Fraqueza", ervas: "Aniz estrelado, canela, erva doce" },
    { nome: "Prosperidade", ervas: "Alecrim, Eucalipto, Manjericão" },
    { nome: "Defesa", ervas: "Espada de São Jorge, Guiné, Alecrim do Campo" },
    { nome: "Amor", ervas: "Sementes de Emburana, Canela em Pó, Pixuri" }
  ],
  por_orixa: [
    { orixa: "Oxalá", ervas: "Tapete de Oxalá (boldo), algodão, arnica da horta, alecrim, folhas e ramos de palmeiras, folhas de laranjeira, hortelã, erva cidreira, rama de leite, malva branca, saião branco, folha da costa, rosa branca, louro, manjerona, manacá, macaça, erva doce" },
    { orixa: "Oxóssi", ervas: "Alfavaca do campo, jureminha, caiçara, arruda, abre caminho, malva rosa, capeba, peregum, taioba, sabugueiro, jurema, capim limão, acácia, cipó caboclo, goiabeira, erva de passarinho, guaco, guiné, malva do campo, são gonçalinho, Louro, cabelo de milho, eucalipto, manjericão, samambaia" },
    { orixa: "Ogum", ervas: "Espada de São Jorge, crista de galo, folhas de mangueira, Taioba, Cipó chumbo, Palmeira de dendezeiro (Mariwo), abre caminho, alfavaquinha, arnica, aroeira, capim limão, carqueja, dandá da costa, erva tostão, eucalipto, jaboticabeira, losna, pau rosa, peregum, porangaba, são gonçalinho, jatobá" },
    { orixa: "Xangô", ervas: "Folha da costa, matamba, betis cheiroso, levante, folha de fogo, cerejeira, figueira branca, amoreira, ameixeira, espada de Santa Bárbara, Comigo ninguém pode, cipó mil homens, folhas de café, folha de manga, Guiné, arruda, limoeiro, umbaúba, vence demanda, urucum, pessegueira, pau pereira, para raio, noz moscada, nega mina, mutamba, mulungu, manjericão, malva cheirosa, jaqueira, folha da fortuna, folha da costa, fedegoso, erva tostão, erva de são João, cavalinha" },
    { orixa: "Iemanjá", ervas: "Jarrinha, Rama de leite, cana do brejo, betis cheiroso, algas marinhas, alfavaquinha, flores branca de qualquer espécie, aguapé, camélia, folha da costa, jasmim, lagrima de nossa senhora, macaça, malva branca, taioba branca" },
    { orixa: "Oxum", ervas: "Folha de vintém, folha da fortuna, malva, dracena, rama de leite, malva rosa, narciso, flores de tonalidade amarela, lírios de toda espécie, margaridas, flor de maio, amor perfeito, madressilva, quioco, oriri, mutamba, melissa, macaça, ipê amarelo, folha da costa, erva de santa Maria, erva de santa luzia, colônia, camomila, assa peixe, aguapé" },
    { orixa: "Iansã", ervas: "Erva santa, umbaúba, folhas de fogo, espada de Santa Bárbara, para-raio, bambu (folhas), pinhão roxo, manjericão, eucalipto, aroeira, arruda" },
    { orixa: "Pretos Velhos", ervas: "Guiné, arruda, alecrim, manjericão, casca de alho, fumo em corda, verbena, cipó caboclo" },
    { orixa: "Exu", ervas: "Pinhão roxo, mamona, urtiga, arruda, guiné, espada de São Jorge, folha de fumo, comigo-ninguém-pode" }
  ],
  classificacao: "Ervas Calmas: Boldo, erva doce, erva cidreira, alecrim do campo, camomila, capim santo, malva branca, malva cheirosa, erva de santa Maria, erva de santa luzia, jasmim, colônia, macaça, aguapé, alfazema, melissa, capim cidrão, folha de maracujá, manjericão, entre outras...\n\nErvas fortes: Arruda, guiné, espada São Jorge, espada de Santa Bárbara, carqueja, aroeira, comigo ninguém pode, peregum, nega mina, umbaúba, mamona, picão branco, eucalipto, pinhão roxo, bambuzinho, taioba, lança de Ogum, espada de Ogum, folha de fumo, entre outras...\n\nErvas bravas: Barba maldita (cipó azougue), unha de gato, comigo ninguém pode, coroa de cristo, mamona, picão preto, urtiga, chorão, folha de limão, folha de seringueira, entre outras...",
  propriedades: "Adstringentes: Contraem as mucosas e tecidos (Açoita cavalo, avenca, goiabeira, nogueira).\n\nAfrodisíacas: Estimulam as forças sexuais geradoras (Agrião, anis, canela, cravo da índia).\n\nAnalgésicas: Acalmam o sofrimento e a dor (Alface, hortelã, guiné, malva).\n\nAntibióticas: Princípios antimicrobianos (Alho, ipê roxo, salsaparrilha).\n\nBéquicas: Combatem a tosse (Agrião, alecrim, guaco, hortelã, poejo).\n\nCalmantes: Exercem a função de acalmar os nervos (Alface, arruda, maracujá, mulungu).\n\nCicatrizantes: Favorecem a cicatrização (Babosa, confrei, camomila, tansagem).\n\nDepurativas: Purificam o sangue (Agrião, chapéu de couro, ipê roxo, sete sangrias).\n\nDigestivas: Facilitam a digestão (Açafrão, boldo, erva cidreira, carqueja).",
  curiosidades: "Trabalho da Água Fria: Quando a água fria toca a pele, os vasos se contraem e a pressão aumenta. Em segundos a pele fica corada e o coração acelera.\n\nTrabalho da Água Quente: A pele fica pálida e logo rosada, facilitando a eliminação de toxinas pela transpiração."
};
